version: '3'

services:

  links:
    image: clckngo_links:latest
    restart: "no"
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/links/Dockerfile

  db:
    image: postgres:12-alpine
    restart: "no"
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
