// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package ports

import (
	"time"
)

// Link defines model for Link.
type Link struct {
	Code string `json:"code"`

	// date-time notation as defined by RFC 3339, section 5.6
	CreatedDatetime time.Time `json:"createdDatetime"`

	// Counter how many times shortened url was opened
	Hits int    `json:"hits"`
	Id   string `json:"id"`

	// date-time notation as defined by RFC 3339, section 5.6
	LastHitDatetime *time.Time `json:"lastHitDatetime"`
	Url             string     `json:"url"`
}

// StoreLinkJSONBody defines parameters for StoreLink.
type StoreLinkJSONBody Link

// StoreLinkJSONRequestBody defines body for StoreLink for application/json ContentType.
type StoreLinkJSONRequestBody StoreLinkJSONBody
